#!/usr/bin/env bash
# install and configure nginx web server

sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo echo "Hellow World!" | tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
