#!/usr/bin/env bash
# install and configure nginx web server

sudo apt-get -y install nginx
sudo touch /usr/share/nginx/html/custom_404.html
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
content="server_name _;\n\trewrite ^\/redirect_me https:\/\/https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html \{\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\}"
sudo sed -i "s/server_name _;/$content/" /etc/nginx/sites-enabled/default
sudo service nginx restart
