#!/usr/bin/env bash
# transfer file to target over ssh connection.

if [ $# -ne 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -4 -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi
