#!/usr/bin/env bash
# Creating a compressed backup of all databases
if [ "$#" -eq 0 ]
then
	mysqldump -u root --all-databases > backup.sql
else
	mysqldump -u root -p "$1" --all-databases > backup.sql
fi
backup_date=$(date +%d-%m-%Y)
sudo tar -cvzf "$backup_date.tar.gz" backup.sql
